#!/bin/bash

# install gbs

# Install remotely via one-liner:
# curl -L gvn.github.com/grunt-build-scaffold/install | bash

cd ~/bin
curl gvn.github.com/grunt-build-scaffold/gbs > gbs
chmod +x gbs

echo "You're all set, dude! Just run 'gbs' to create a new project."