#!/bin/bash

# install gbs

# Install remotely via one-liner:
# curl -L gvn.github.com/grunt-build-scaffold/install | bash

cd ~/bin
curl gvn.github.com/grunt-build-scaffold/gbs > gbs
chmod +x gbs

echo -e "\n\nYou're all set, dude.\n\nJust run 'gbs' to create a new project.\n"